site_name: Central de ajuda

nav:
  - O que é a plataforma Indexa?: index.md
  - Criando meu site:
    - Criação de conta: criando-meu-site/criacao-de-conta.md
    - Formulário de criação: criando-meu-site/formulario-de-criacao.md
  - Visualizndo meu site: visualizando-meu-site.md        
  - Editando meu site:
    - Editar informações: editando-meu-site/editar-informacoes.md
    - Adicionar ou remover serviços: editando-meu-site/adicionar-ou-remover-servicos.md    
    - Mudar template e aparência: editando-meu-site/mudar-template-e-aparencia.md
    - Logo na aba do navegador: editando-meu-site/logo-na-aba-do-navegador.md
    - Modo invisível: editando-meu-site/modo-invisivel.md 
    - Limpar cache do nevegador: editando-meu-site/limpar-cache-do-navegador.md
  - Domínio personalizado:  
    - Como comprar um domínio?: dominio-personalizado/como-comprar-um-dominio.md
    - Definir domínio personalizado: dominio-personalizado/definir-dominio-personalizado.md
  - Ativando certificado SSL:  ativando-certificado-ssl.md
  - Otimização para motores de busca (SEO):  otimizacao-para-motores-de-busca-seo.md

theme:
  name: "material"
  language: pt-BR
  logo: https://d2qk6l2gc5y036.cloudfront.net/indexa-mfe-library/shared-assets/indexaLogo.png

extra_css:
  - stylesheets/extra.css